// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: posts.proto

package server

import (
	"context"

	"testGoZero/posts/internal/logic"
	"testGoZero/posts/internal/svc"
	"testGoZero/posts/posts"
)

type PostServiceServer struct {
	svcCtx *svc.ServiceContext
	posts.UnimplementedPostServiceServer
}

func NewPostServiceServer(svcCtx *svc.ServiceContext) *PostServiceServer {
	return &PostServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PostServiceServer) CreatePost(ctx context.Context, in *posts.PostInfoReq) (*posts.PostInfoResp, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *PostServiceServer) GetPost(ctx context.Context, in *posts.SinglePostInfoReq) (*posts.SinglePostInfoResp, error) {
	l := logic.NewGetPostLogic(ctx, s.svcCtx)
	return l.GetPost(in)
}

func (s *PostServiceServer) ListPosts(ctx context.Context, in *posts.PageReq) (*posts.SelectPostInfoResp, error) {
	l := logic.NewListPostsLogic(ctx, s.svcCtx)
	return l.ListPosts(in)
}

func (s *PostServiceServer) UpdatePost(ctx context.Context, in *posts.PostInfoReq) (*posts.PostInfoResp, error) {
	l := logic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

func (s *PostServiceServer) DeletePost(ctx context.Context, in *posts.PostInfoReq) (*posts.PostInfoResp, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}
