// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: users.proto

package server

import (
	"context"
	"rpc/users/internal/logic"
	"rpc/users/internal/svc"
	"rpc/users/users"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	users.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Register(ctx context.Context, in *users.RegisterUserInfoReq) (*users.RegisterUserInfoResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) Login(ctx context.Context, in *users.LoginUserInfoReq) (*users.LoginUserInfoResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
