// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: users.proto

package users

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== Users Service ==========
type RegisterUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserInfoReq) Reset() {
	*x = RegisterUserInfoReq{}
	mi := &file_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserInfoReq) ProtoMessage() {}

func (x *RegisterUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserInfoReq.ProtoReflect.Descriptor instead.
func (*RegisterUserInfoReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserInfoReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegisterUserInfoReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserInfoReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          bool                   `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserInfoResp) Reset() {
	*x = RegisterUserInfoResp{}
	mi := &file_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserInfoResp) ProtoMessage() {}

func (x *RegisterUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserInfoResp.ProtoReflect.Descriptor instead.
func (*RegisterUserInfoResp) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserInfoResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *RegisterUserInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type LoginUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserInfoReq) Reset() {
	*x = LoginUserInfoReq{}
	mi := &file_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserInfoReq) ProtoMessage() {}

func (x *LoginUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserInfoReq.ProtoReflect.Descriptor instead.
func (*LoginUserInfoReq) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{2}
}

func (x *LoginUserInfoReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginUserInfoReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          bool                   `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,json=Msg,proto3" json:"msg,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserInfoResp) Reset() {
	*x = LoginUserInfoResp{}
	mi := &file_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserInfoResp) ProtoMessage() {}

func (x *LoginUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserInfoResp.ProtoReflect.Descriptor instead.
func (*LoginUserInfoResp) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{3}
}

func (x *LoginUserInfoResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *LoginUserInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginUserInfoResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_users_proto protoreflect.FileDescriptor

const file_users_proto_rawDesc = "" +
	"\n" +
	"\vusers.proto\x12\x05users\x1a\x1cgoogle/api/annotations.proto\"d\n" +
	"\x13RegisterUserInfoReq\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"<\n" +
	"\x14RegisterUserInfoResp\x12\x12\n" +
	"\x04flag\x18\x01 \x01(\bR\x04flag\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"K\n" +
	"\x10LoginUserInfoReq\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"O\n" +
	"\x11LoginUserInfoResp\x12\x12\n" +
	"\x04flag\x18\x01 \x01(\bR\x04flag\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03Msg\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token2\xc1\x01\n" +
	"\vUserService\x12^\n" +
	"\bRegister\x12\x1a.users.RegisterUserInfoReq\x1a\x1b.users.RegisterUserInfoResp\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/user/register\x12R\n" +
	"\x05Login\x12\x17.users.LoginUserInfoReq\x1a\x18.users.LoginUserInfoResp\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/user/loginB\tZ\a./usersb\x06proto3"

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData []byte
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)))
	})
	return file_users_proto_rawDescData
}

var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_users_proto_goTypes = []any{
	(*RegisterUserInfoReq)(nil),  // 0: users.RegisterUserInfoReq
	(*RegisterUserInfoResp)(nil), // 1: users.RegisterUserInfoResp
	(*LoginUserInfoReq)(nil),     // 2: users.LoginUserInfoReq
	(*LoginUserInfoResp)(nil),    // 3: users.LoginUserInfoResp
}
var file_users_proto_depIdxs = []int32{
	0, // 0: users.UserService.Register:input_type -> users.RegisterUserInfoReq
	2, // 1: users.UserService.Login:input_type -> users.LoginUserInfoReq
	1, // 2: users.UserService.Register:output_type -> users.RegisterUserInfoResp
	3, // 3: users.UserService.Login:output_type -> users.LoginUserInfoResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
