// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type LoginUserInfoReq struct {
	UsernName string `json:"userName"`
	Password  string `json:"password"`
}

type LoginUserInfoResp struct {
	Flag  bool   `json:"flag"`
	Msg   string `json:"Msg"`
	Token string `json:"token"`
}

type PageReq struct {
	Page     uint64 `form:"page,default=1"`      // 默认第1页
	PageSize uint64 `form:"pageSize,default=10"` // 默认每页10条
}

type PageResp struct {
	CurrentPage uint64 `json:"currentPage"` // 当前页码
	PageSize    uint64 `json:"pageSize"`    // 每页数量
	Total       uint64 `json:"total"`       // 总记录数
	TotalPages  uint64 `json:"totalPages"`  // 总页数
}

type PostInfoReq struct {
	Title   string `json:"title" validate:"required"`
	Content string `json:"content" validate:"required"`
}

type PostInfoResp struct {
	Flag bool   `json:"flag"`
	Msg  string `json:"msg"`
}

type RegisterUserInfoReq struct {
	UsernName string `json:"userName" validate:"required"`
	Password  string `json:"password" validate:"required"`
	Email     string `json:"email" validate:"required,email"`
}

type RegisterUserInfoResp struct {
	Flag bool   `json:"flag"`
	Msg  string `json:"msg"`
}

type SelectPostInfoResp struct {
	PageResp
	Data []SinglePostInfoResp `json:"data"`
}

type SinglePostInfoReq struct {
	Id uint64 `path:"id"`
}

type SinglePostInfoResp struct {
	Id            uint64 `json:"id"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	UserId        uint64 `json:"userId"`
	CommentStatus string `json:"commentStatus"`
}
