// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: posts.proto

package posts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== Posts Service ==========
type PostInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoReq) Reset() {
	*x = PostInfoReq{}
	mi := &file_posts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoReq) ProtoMessage() {}

func (x *PostInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoReq.ProtoReflect.Descriptor instead.
func (*PostInfoReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{0}
}

func (x *PostInfoReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostInfoReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PostInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          bool                   `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfoResp) Reset() {
	*x = PostInfoResp{}
	mi := &file_posts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfoResp) ProtoMessage() {}

func (x *PostInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfoResp.ProtoReflect.Descriptor instead.
func (*PostInfoResp) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{1}
}

func (x *PostInfoResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *PostInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SinglePostInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinglePostInfoReq) Reset() {
	*x = SinglePostInfoReq{}
	mi := &file_posts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinglePostInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinglePostInfoReq) ProtoMessage() {}

func (x *SinglePostInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinglePostInfoReq.ProtoReflect.Descriptor instead.
func (*SinglePostInfoReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{2}
}

func (x *SinglePostInfoReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SinglePostInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CommentStatus string                 `protobuf:"bytes,5,opt,name=comment_status,json=commentStatus,proto3" json:"comment_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinglePostInfoResp) Reset() {
	*x = SinglePostInfoResp{}
	mi := &file_posts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinglePostInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinglePostInfoResp) ProtoMessage() {}

func (x *SinglePostInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinglePostInfoResp.ProtoReflect.Descriptor instead.
func (*SinglePostInfoResp) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{3}
}

func (x *SinglePostInfoResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SinglePostInfoResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SinglePostInfoResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SinglePostInfoResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SinglePostInfoResp) GetCommentStatus() string {
	if x != nil {
		return x.CommentStatus
	}
	return ""
}

type PageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageReq) Reset() {
	*x = PageReq{}
	mi := &file_posts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReq) ProtoMessage() {}

func (x *PageReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReq.ProtoReflect.Descriptor instead.
func (*PageReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{4}
}

func (x *PageReq) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageReq) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   uint64                 `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    uint64                 `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResp) Reset() {
	*x = PageResp{}
	mi := &file_posts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResp) ProtoMessage() {}

func (x *PageResp) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResp.ProtoReflect.Descriptor instead.
func (*PageResp) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{5}
}

func (x *PageResp) GetCurrentPage() uint64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PageResp) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageResp) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageResp) GetTotalPages() uint64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type SelectPostInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageInfo      *PageResp              `protobuf:"bytes,1,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	Data          []*SinglePostInfoResp  `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectPostInfoResp) Reset() {
	*x = SelectPostInfoResp{}
	mi := &file_posts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectPostInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectPostInfoResp) ProtoMessage() {}

func (x *SelectPostInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectPostInfoResp.ProtoReflect.Descriptor instead.
func (*SelectPostInfoResp) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{6}
}

func (x *SelectPostInfoResp) GetPageInfo() *PageResp {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *SelectPostInfoResp) GetData() []*SinglePostInfoResp {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_posts_proto protoreflect.FileDescriptor

const file_posts_proto_rawDesc = "" +
	"\n" +
	"\vposts.proto\x12\x05posts\"=\n" +
	"\vPostInfoReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"4\n" +
	"\fPostInfoResp\x12\x12\n" +
	"\x04flag\x18\x01 \x01(\bR\x04flag\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"#\n" +
	"\x11SinglePostInfoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x94\x01\n" +
	"\x12SinglePostInfoResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12%\n" +
	"\x0ecomment_status\x18\x05 \x01(\tR\rcommentStatus\":\n" +
	"\aPageReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\"\x81\x01\n" +
	"\bPageResp\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x04R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x04R\n" +
	"totalPages\"q\n" +
	"\x12SelectPostInfoResp\x12,\n" +
	"\tpage_info\x18\x01 \x01(\v2\x0f.posts.PageRespR\bpageInfo\x12-\n" +
	"\x04data\x18\x02 \x03(\v2\x19.posts.SinglePostInfoRespR\x04data2\xaa\x02\n" +
	"\vPostService\x125\n" +
	"\n" +
	"CreatePost\x12\x12.posts.PostInfoReq\x1a\x13.posts.PostInfoResp\x12>\n" +
	"\aGetPost\x12\x18.posts.SinglePostInfoReq\x1a\x19.posts.SinglePostInfoResp\x126\n" +
	"\tListPosts\x12\x0e.posts.PageReq\x1a\x19.posts.SelectPostInfoResp\x125\n" +
	"\n" +
	"UpdatePost\x12\x12.posts.PostInfoReq\x1a\x13.posts.PostInfoResp\x125\n" +
	"\n" +
	"DeletePost\x12\x12.posts.PostInfoReq\x1a\x13.posts.PostInfoRespB\tZ\a./postsb\x06proto3"

var (
	file_posts_proto_rawDescOnce sync.Once
	file_posts_proto_rawDescData []byte
)

func file_posts_proto_rawDescGZIP() []byte {
	file_posts_proto_rawDescOnce.Do(func() {
		file_posts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_posts_proto_rawDesc), len(file_posts_proto_rawDesc)))
	})
	return file_posts_proto_rawDescData
}

var file_posts_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_posts_proto_goTypes = []any{
	(*PostInfoReq)(nil),        // 0: posts.PostInfoReq
	(*PostInfoResp)(nil),       // 1: posts.PostInfoResp
	(*SinglePostInfoReq)(nil),  // 2: posts.SinglePostInfoReq
	(*SinglePostInfoResp)(nil), // 3: posts.SinglePostInfoResp
	(*PageReq)(nil),            // 4: posts.PageReq
	(*PageResp)(nil),           // 5: posts.PageResp
	(*SelectPostInfoResp)(nil), // 6: posts.SelectPostInfoResp
}
var file_posts_proto_depIdxs = []int32{
	5, // 0: posts.SelectPostInfoResp.page_info:type_name -> posts.PageResp
	3, // 1: posts.SelectPostInfoResp.data:type_name -> posts.SinglePostInfoResp
	0, // 2: posts.PostService.CreatePost:input_type -> posts.PostInfoReq
	2, // 3: posts.PostService.GetPost:input_type -> posts.SinglePostInfoReq
	4, // 4: posts.PostService.ListPosts:input_type -> posts.PageReq
	0, // 5: posts.PostService.UpdatePost:input_type -> posts.PostInfoReq
	0, // 6: posts.PostService.DeletePost:input_type -> posts.PostInfoReq
	1, // 7: posts.PostService.CreatePost:output_type -> posts.PostInfoResp
	3, // 8: posts.PostService.GetPost:output_type -> posts.SinglePostInfoResp
	6, // 9: posts.PostService.ListPosts:output_type -> posts.SelectPostInfoResp
	1, // 10: posts.PostService.UpdatePost:output_type -> posts.PostInfoResp
	1, // 11: posts.PostService.DeletePost:output_type -> posts.PostInfoResp
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_posts_proto_init() }
func file_posts_proto_init() {
	if File_posts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_posts_proto_rawDesc), len(file_posts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_posts_proto_goTypes,
		DependencyIndexes: file_posts_proto_depIdxs,
		MessageInfos:      file_posts_proto_msgTypes,
	}.Build()
	File_posts_proto = out.File
	file_posts_proto_goTypes = nil
	file_posts_proto_depIdxs = nil
}
